name = "authenticated-worker-proxy"
main = "src/index.ts"
compatibility_date = "2026-09-01"

# Allow all public websites by default (or specify comma-separated list of domains/URLs)
[vars]
UPSTREAM_ALLOWLIST = "*"
